spring.application.name=register


# JWT 보안 설정
JWT_SECRET=travel_secret_master_key_0123456789
JWT_EXPIRATION=3600000

#  H2 데이터베이스 설정
spring.datasource.url=jdbc:h2:file:./data/testdb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=1234
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


#  JPA/Hibernate 설정
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

#  Swagger UI 경로 설정
springdoc.swagger-ui.path=/swagger-ui.html